spring:
  profiles:
    active:
      - dog
      - EN
      - dev
guru:
  username: YmlUsername
  password: YmlPassword
  jdbcurl: YmlUrlforDB

---
spring:
  profiles: prod
guru:
  username: YmlProdUsername
  password: YmlProdPassword
  jdbcurl: YmlProdUrlforDB